Improvement for script & template sandbox:
craftercms/engine pull request #522
Opened 2021-05-26 22:05 UTC by jdrossl

- Add new restrictions for both Groovy & Freemarker

https://github.com/craftersoftware/craftercms/issues/240

Depends on https://github.com/craftercms/script-security-plugin/pull/13

2021-05-27 20:02 UTC, avasquez614 requested changes

2021-05-27 20:02 UTC, avasquez614 commented on src/main/resources/crafter/engine/server-config.properties
> +# Indicates if the blacklist should be enabled for all sites
Please add doc indicating this variable only works if sandbox is enabled

2021-05-27 20:02 UTC, avasquez614 commented on src/main/resources/crafter/engine/server-config.properties
> +# The location of the default blacklist to use for all sites
Please add doc indicating this variable only works if sandbox is enabled

2021-05-28 14:20 UTC, sumerjabri approved these changes

2021-05-28 14:27 UTC, merged