Improve API response in not found response use case #344
craftercms/engine pull request #592
Opened 2022-07-20 20:37 UTC by jmendeza

https://github.com/craftersoftware/craftercms/issues/344

Improve API response in not found response use case

2022-08-12 19:15 UTC, sumerjabri approved these changes

2022-08-22 15:31 UTC, avasquez614 requested changes

2022-08-22 15:31 UTC, avasquez614 commented on src/main/java/org/craftercms/engine/controller/rest/RestScriptsController.java
> +    protected static final String REST_SERVICES_ROOT = "/api/1/services";
It also needs to map to `/api/*`. That's the main root clients use now.

2022-08-23 14:48 UTC, avasquez614 approved these changes

2022-08-23 15:56 UTC, merged