Make sure all test run
craftercms/engine pull request #678
Opened 2023-11-06 05:54 UTC by phuongnq

### Ticket reference or full description of what's in the PR
https://github.com/craftercms/craftercms/issues/6243

2023-11-06 15:27 UTC, jmendeza requested changes

2023-11-06 15:27 UTC, jmendeza commented on src/test/java/org/craftercms/engine/test/utils/ContextMockUtils.java
> +    public static Context createContext() {
Can we use Mockito instead?
```
Mockito.mock(Context.class)
```

2023-11-07 01:24 UTC, phuongnq commented on src/test/java/org/craftercms/engine/test/utils/ContextMockUtils.java
> +    public static Context createContext() {
Updated to use mockito

2023-11-07 16:31 UTC, jmendeza approved these changes

2023-11-07 17:31 UTC, merged