Support variables in configuration files
craftercms/engine pull request #719
Opened 2024-03-16 00:16 UTC by jmendeza

https://github.com/craftercms/craftercms/issues/6624
Support variables in configuration files

2024-03-27 21:33 UTC, avasquez614 approved these changes

2024-04-01 18:17 UTC, sumerjabri requested changes

2024-04-01 18:17 UTC, sumerjabri commented on src/test/java/org/craftercms/engine/scripting/impl/ConfigurationScriptJobResolverTest.java
> +            ConfigUtils.readXmlConfiguration(new ClassPathResource("config/site-config.xml"), ',', null, null);
Should we add unit tests for the new features?

2024-04-05 17:40 UTC, sumerjabri approved these changes

2024-04-09 14:50 UTC, merged